fixed typo in deferred_conditioned_scale (#1812)
* fixed typo in deferred_conditioned_scale

The original definition of deferred_conditioned_scale gave "TypeError: scale() missing 1 required positional argument: 'guess'" when fed to pyro.infer.SVI in place of conditioend_scale later in the tutorial this way:
```python
conditioned_scale1 = deferred_conditioned_scale(
    measurement=9.5,
)

pyro.clear_param_store()
svi = pyro.infer.SVI(model=conditioned_scale1,
                     guide=scale_parametrized_guide_constrained,
                     optim=pyro.optim.SGD({"lr": 0.001, "momentum":0.1}),
                     loss=pyro.infer.Trace_ELBO())
```
The new version runs without an error and gives the same results as `conditioned_scale`

* Update intro_part_ii.ipynb

Thank you for the explanation! I changed it as suggested. I think it might be helpful to give an example guide for `deferred_conditioned_scale` as well in the tutorial, or point to the relevant material (as you thankfully did).